use_cols = ['Account',
            'Item Number',
            'Item Description',
            'Warehouse',
            'Location',
            'Onhand Qty',
            'Reserved Qty',
            'Available Qty',
            'Vendor Serial',
            'Vendor Lot',
            'LPN',
            'Revision',
            'Date Received GMT',
            'Rec Ref 1',
            'Rec Ref 2',
            'Rec Ref 3',
            'Attribute 1',
            'Attribute 3',
            'Attribute 4',
            'Attribute 6']
