CREATE OR REPLACE VIEW dm_commercial.v_activity_retention_rental_plan AS
WITH journey AS (
	SELECT DISTINCT  
		s.subscription_id, 
		max(CASE WHEN s2.start_date<s.start_date THEN s2.start_date END) AS start_of_previous_sub,
		max(case when s2.cancellation_date<s.start_date THEN s2.cancellation_date END) AS cancell_previous_sub
	FROM master.subscription s
	LEFT JOIN master.subscription s2 
		ON s.customer_id=s2.customer_id
	GROUP BY 1
)
, days_to_return AS ( 
	SELECT 
		 customer_id, 
		 s.subscription_id, 
		 s.order_id,
		 rank_subscriptions, 
		 start_date, 
		 s.cancellation_date, 
		 s.retention_group,
		 j.start_of_previous_sub,
		 j.cancell_previous_sub,
		 CASE WHEN retention_group = 'RECURRING, REACTIVATION' THEN cancell_previous_sub 
		  	WHEN retention_group = 'RECURRING, UPSELL' THEN start_of_previous_sub 
		  	END AS previous_date,
		 DATE_DIFF('day',previous_date , start_date) AS days_to_return
	FROM master.subscription s 
	LEFT JOIN journey j 
		ON j.subscription_id=s.subscription_id	
)
SELECT 
	s.account_name , 
	c.acquired_subscription_plan , 
	c.additional_charge_paid , 
	s.allocated_assets , 
	s.allocation_status , 
	s.allocation_tries , 
	c.amount_due , 
	c.amount_paid , 
	s.asset_cashflow_from_old_subscriptions , 
	s.asset_recirculation_status , 
	s.avg_asset_purchase_price , 
	s.brand , 
	d.cancell_previous_sub , 
	s.cancellation_date , 
	s.cancellation_reason , 
	c.cancellation_reason_churn , 
	s.cancellation_reason_new , 
	d.cancellation_date AS cancellation_date_custom_sql_query, 
	s.cancellation_note , 
	s.category_name , 
	c.chargeback_paid , 
	s.commited_sub_revenue_future ,  
	(s.committed_sub_value + s.additional_committed_sub_value) as committed_sub_value , 
	s.country_name , 
	s.created_date , 
	s.cross_sale_attempts , 
	s.currency , 
	c.customer_acquisition_cohort , 
	c.customer_bought_paid , 
	c.customer_id , 
	c.customer_type , 
	c.customer_acquisition_store , 
	c.days_between_acquisition_due , 
	c.days_between_acquisition_paid , 
	d.days_to_return , 
	s.dc_status , 
	s.debt_collection_handover_date , 
	s.delivered_assets , 
	c.discount_amount , 
	s.dpd , 
	c.due_date , 
	s.effective_duration , 
	s.exposure_to_default , 
	s.first_asset_delivery_date , 
	s.first_subscription_start_date , 
	c.first_due_date , 
	c.is_customer_default , 
	s.is_not_triggered_payments , 
	c.is_subscription_default , 
	s.is_widerruf , 
	s.is_eligible_for_mietkauf , 
	s.last_return_shipment_at , 
	s.last_valid_payment_category , 
	s.max_payment_number , 
	s.mietkauf_amount_overpayment , 
	s.minimum_cancellation_date , 
	s.minimum_term_months , 
	c.months_between_acquisition_due , 
	s.months_required_to_own , 
	s.net_subscription_revenue_paid ,  
	c.new_recurring , 
	s.next_due_date ,  
	s.order_id , 
	c.order_status , 
	s.order_created_date , 
	d.order_id AS order_id_custom_sql_query , 
	s.outstanding_asset_value , 
	s.outstanding_assets , 
	s.outstanding_duration , 
	s.outstanding_rrp , 
	s.outstanding_subscription_revenue , 
	s.outstanding_residual_asset_value , 
	c.paid_date , 
	s.paid_subscriptions , 
	c.paid_orders_with_voucher , 
	s.payment_count , 
	s.payment_method , 
	c.payment_status , 
	c.payment_type , 
	c.payment_id , 
	s.product_name , 
	s.product_sku ,  
	d.rank_subscriptions , 
	c.refunds_paid , 
	s.rental_period , 
	c.repair_cost_paid , 
	s.replacement_attempts , 
	s.result_debt_collection_contact ,  
	d.retention_group , 
	s.returned_assets , 
	s.returned_packages , 
	c.shipment_cost_paid , 
	c.special_voucher_of_first_order , 
	s.start_date , 
	d.start_date AS start_date_custom_sql_query , 
	d.start_of_previous_sub , 
	s.status , 
	s.store_label , 
	s.store_name , 
	s.store_commercial , 
	s.store_id , 
	s.store_number , 
	s.store_short , 
	s.store_type , 
	s.subcategory_name , 
	s.subscription_duration ,  
	c.subscription_id , 
	mc.subscription_limit ,  
	s.subscription_plan , 
	s.subscription_revenue_chargeback , 
	s.subscription_revenue_due , 
	s.subscription_revenue_paid , 
	s.subscription_revenue_refunded , 
	s.subscription_sf_id ,  
	s.subscription_value , 
	d.subscription_id AS subscription_id_custom_sql_query, 
	s.subscriptions_per_customer , 
	c.total_voucher_discount , 
	s.trial_days , 
	s.trial_variant , 
	c.unique_special_vouchers_redeemed , 
	c.unique_vouchers_redeemed , 
	s.updated_date , 
	s.variant_sku ,
	mc.company_id , 
	mc.created_at , 
	mc.updated_at , 
	mc.subscription_limit_change_date , 
	mc.company_name , 
	mc.company_status , 
	mc.company_type_name , 
	mc.company_created_at , 
	mc.billing_country , 
	mc.shipping_country , 
	mc.billing_city , 
	mc.billing_zip , 
	mc.shipping_city , 
	mc.shipping_zip , 
	mc.signup_language , 
	mc.default_locale , 
	mc.bundesland , 
	mc.referral_code , 
	mc.email_subscribe , 
	mc.initial_subscription_limit , 
	mc.subscription_limit_defined_date , 
	mc.customer_scoring_result , 
	mc.burgel_score , 
	mc.burgel_score_details , 
	mc.burgel_person_known , 
	mc.burgel_address_details , 
	mc.verita_score , 
	mc.verita_person_known_at_address , 
	mc.fraud_type , 
	mc.trust_type , 
	mc.min_fraud_detected , 
	mc.max_fraud_detected , 
	mc.schufa_class , 
	mc.orders , 
	mc.completed_orders , 
	mc.paid_orders , 
	mc.declined_orders , 
	mc.last_order_created_date , 
	mc.last_cart_product_names , 
	mc.max_submitted_order_date , 
	mc.delivered_allocations , 
	mc.returned_allocations , 
	mc.outstanding_purchase_price , 
	mc.active_subscription_product_names , 
	mc.active_subscription_subcategory , 
	mc.active_subscription_category , 
	mc.active_subscription_brand , 
	mc.ever_rented_asset_purchase_price , 
	mc.active_subscription_value , 
	mc.committed_subscription_value , 
	mc.active_subscriptions ,  
	mc.refunded_subscriptions , 
	mc.failed_subscriptions , 
	mc.chargeback_subscriptions , 
	mc.burgel_risk_category , 
	mc.subscriptions , 
	mc.start_date_of_first_subscription , 
	mc.first_subscription_store , 
	mc.first_subscription_acquisition_channel , 
	mc.second_subscription_store , 
	mc.subscription_durations , 
	mc.first_subscription_duration , 
	mc.second_subscription_duration , 
	mc.subs_wearables , 
	mc.subs_drones , 
	mc.subs_cameras , 
	mc.subs_phones_and_tablets , 
	mc.subs_computers , 
	mc.subs_gaming , 
	mc.subs_audio , 
	mc.subs_other , 
	mc.first_subscription_product_category , 
	mc.second_subscription_product_category , 
	mc.ever_rented_products , 
	mc.ever_rented_sku , 
	mc.ever_rented_brands , 
	mc.ever_rented_subcategories , 
	mc.ever_rented_categories , 
	mc.clv , 
	mc.voucher_usage , 
	mc.minimum_cancellation_product , 
	mc.subs_pag , 
	mc.subs_1m , 
	mc.subs_3m , 
	mc.subs_6m , 
	mc.subs_12m , 
	mc.subs_24m , 
	mc.is_bad_customer , 
	mc.customer_acquisition_subscription_id , 
	mc.customer_acquisition_rental_plan , 
	mc.customer_acquisition_category_name AS customer_acquisition_category , 
	mc.customer_acquisition_subcategory_name , 
	mc.customer_acquisition_product_brand , 
	mc.rfm_score , 
	mc.rfm_segment , 
	mc.signup_country , 
	mc.max_cancellation_date , 
	mc.max_asset_delivered_at , 
	mc.crm_label , 
	mc.profile_status , 
	mc."age"
FROM dwh.customer_collection_curves c
LEFT JOIN master.customer mc
	ON mc.customer_id = c.customer_id
LEFT JOIN master.subscription s 
	ON  c.subscription_id = s.subscription_id
LEFT JOIN days_to_return d 
	ON s.subscription_id = d.subscription_id
WITH NO SCHEMA BINDING;



