delete from staging.stream_shipping_shipcloud_incoming_notification
where event_timestamp::date >= current_date::date-1;

insert into staging.stream_shipping_shipcloud_incoming_notification
  with ct as(
	SELECT
		kafka_received_at::timestamp AS event_timestamp,
		event_name ,
		JSON_EXTRACT_PATH_text(payload ,'shipment') AS shipment,
		JSON_EXTRACT_PATH_text(shipment,'id') AS shipment_id ,
		JSON_EXTRACT_PATH_text(payload ,'type') AS "type",
		JSON_EXTRACT_PATH_text(shipment,'original') AS original,
		JSON_EXTRACT_PATH_text(original,'created_at') AS original_created_at,
		JSON_EXTRACT_PATH_text(original,'to') AS original_to,
		JSON_EXTRACT_PATH_text(original,'from') AS original_from,
		JSON_EXTRACT_PATH_text(original,'id') AS original_id ,
		JSON_EXTRACT_PATH_text(original,'carrier') AS original_carrier ,
		JSON_EXTRACT_PATH_text(original,'price') AS original_price,
		JSON_EXTRACT_PATH_text(original,'label_url') AS original_label_url,
		JSON_EXTRACT_PATH_text(original,'carrier_tracking_no') AS original_carrier_tracking_no,
		JSON_EXTRACT_PATH_text(original,'reference_number') AS original_reference_number,
		JSON_EXTRACT_PATH_text(original,'tracking_url') AS original_tracking_url,
		JSON_EXTRACT_PATH_text(original,'service') AS original_service,
		JSON_EXTRACT_PATH_text(original,'additional_services') AS original_additional_services,
		JSON_EXTRACT_PATH_text(original,'metadata') AS original_metadata,
		JSON_EXTRACT_PATH_text(original,'packages') AS original_packages,
		JSON_EXTRACT_PATH_text(shipment,'unified') AS unified,
		JSON_EXTRACT_PATH_text(unified,'id') AS unified_id ,
		JSON_EXTRACT_PATH_text(unified,'carrier') AS unified_carrier ,
		JSON_EXTRACT_PATH_text(unified,'to') AS unified_to,
		JSON_EXTRACT_PATH_text(unified,'from') AS unified_from,
		JSON_EXTRACT_PATH_text(unified,'price') AS unified_price,
		JSON_EXTRACT_PATH_text(unified,'created_at') AS unified_created_at,
		JSON_EXTRACT_PATH_text(unified,'label_url') AS unified_label_url,
		JSON_EXTRACT_PATH_text(unified,'carrier_tracking_no') AS unified_carrier_tracking_no,
		JSON_EXTRACT_PATH_text(unified,'tracking_url') AS unified_tracking_url,
		JSON_EXTRACT_PATH_text(unified,'service') AS unified_service,
		JSON_EXTRACT_PATH_text(unified,'metadata') AS unified_metadata,
		JSON_EXTRACT_PATH_text(unified,'packages') AS unified_packages,
		JSON_EXTRACT_PATH_text(unified,'additional_services') AS unified_additional_services,
		JSON_EXTRACT_PATH_text(unified,'reference_number') AS unified_reference_number,
		JSON_EXTRACT_PATH_text(payload,'data') AS "data"
	FROM s3_spectrum_kafka_topics_raw.shipping_shipcloud_incoming_notification
  where CAST(("year" || '-' || "month" || '-' || "day") AS date) >= current_date::date-1
    AND event_timestamp >= current_date-2
    AND is_valid_json(payload)
  )
select shipment_id ,original_id ,original_price ,unified_created_at ,
    original_label_url ,original_carrier_tracking_no ,unified_carrier_tracking_no ,
    original_reference_number ,unified_label_url,type ,unified_service,event_name,unified_price,original_service,
    unified_tracking_url,unified_id,unified_reference_number , event_timestamp ,
    unified_additional_services ,unified_carrier,unified_metadata,unified_packages,
    original_metadata,
    original_tracking_url ,original_carrier ,original_created_at ,
    original_additional_services,
    JSON_EXTRACT_PATH_text(data, 'id') as data_id,
    JSON_EXTRACT_PATH_text(data, 'url') as data_url,
    JSON_EXTRACT_PATH_text(data, 'object_type') as data_object_type,
    JSON_EXTRACT_PATH_text(unified_to, 'company') as unified_to_company,
    JSON_EXTRACT_PATH_text(unified_to, 'first_name') as unified_to_first_name,
    JSON_EXTRACT_PATH_text(unified_to, 'last_name') as unified_to_last_name,
    JSON_EXTRACT_PATH_text(unified_to, 'care_of') as unified_to_care_of,
    JSON_EXTRACT_PATH_text(unified_to, 'street') as unified_to_street,
    JSON_EXTRACT_PATH_text(unified_to, 'street_no') as unified_to_street_no,
    JSON_EXTRACT_PATH_text(unified_to, 'zip_code') as unified_to_zip_code,
    JSON_EXTRACT_PATH_text(unified_to, 'city') as unified_to_city,
    JSON_EXTRACT_PATH_text(unified_to, 'country') as unified_to_country,
    JSON_EXTRACT_PATH_text(unified_to, 'phone') as unified_to_phone,
    JSON_EXTRACT_PATH_text(unified_to, 'email') as unified_to_email,
    JSON_EXTRACT_PATH_text(unified_to, 'id') as unified_to_id,
    JSON_EXTRACT_PATH_text(unified_from, 'company') as unified_from_company,
    JSON_EXTRACT_PATH_text(unified_from, 'first_name') as unified_from_first_name,
    JSON_EXTRACT_PATH_text(unified_from, 'last_name') as unified_from_last_name,
    JSON_EXTRACT_PATH_text(unified_from, 'care_of') as unified_from_care_of,
    JSON_EXTRACT_PATH_text(unified_from, 'street') as unified_from_street,
    JSON_EXTRACT_PATH_text(unified_from, 'street_no') as unified_from_street_no,
    JSON_EXTRACT_PATH_text(unified_from, 'zip_code') as unified_from_zip_code,
    JSON_EXTRACT_PATH_text(unified_from, 'city') as unified_from_city,
    JSON_EXTRACT_PATH_text(unified_from, 'country') as unified_from_country,
    JSON_EXTRACT_PATH_text(unified_from, 'phone') as unified_from_phone,
    JSON_EXTRACT_PATH_text(unified_from, 'email') as unified_from_email,
    JSON_EXTRACT_PATH_text(unified_from, 'id') as unified_from_id,
    JSON_EXTRACT_PATH_text(original_from, 'company') as original_from_company,
    JSON_EXTRACT_PATH_text(original_from, 'first_name') as original_from_first_name,
    JSON_EXTRACT_PATH_text(original_from, 'last_name') as original_from_last_name,
    JSON_EXTRACT_PATH_text(original_from, 'care_of') as original_from_care_of,
    JSON_EXTRACT_PATH_text(original_from, 'street') as original_from_street,
    JSON_EXTRACT_PATH_text(original_from, 'street_no') as original_from_street_no,
    JSON_EXTRACT_PATH_text(original_from, 'zip_code') as original_from_zip_code,
    JSON_EXTRACT_PATH_text(original_from, 'city') as original_from_city,
    JSON_EXTRACT_PATH_text(original_from, 'country') as original_from_country,
    JSON_EXTRACT_PATH_text(original_from, 'phone') as original_from_phone,
    JSON_EXTRACT_PATH_text(original_from, 'email') as original_from_email,
    JSON_EXTRACT_PATH_text(original_from, 'id') as original_from_id,
    JSON_EXTRACT_PATH_text(original_to, 'company') as original_to_company,
    JSON_EXTRACT_PATH_text(original_to, 'first_name') as original_to_first_name,
    JSON_EXTRACT_PATH_text(original_to, 'last_name') as original_to_last_name,
    JSON_EXTRACT_PATH_text(original_to, 'care_of') as original_to_care_of,
    JSON_EXTRACT_PATH_text(original_to, 'street') as original_to_street,
    JSON_EXTRACT_PATH_text(original_to, 'street_no') as original_to_street_no,
    JSON_EXTRACT_PATH_text(original_to, 'zip_code') as original_to_zip_code,
    JSON_EXTRACT_PATH_text(original_to, 'city') as original_to_city,
    JSON_EXTRACT_PATH_text(original_to, 'country') as original_to_country,
    JSON_EXTRACT_PATH_text(original_to, 'phone') as original_to_phone,
    JSON_EXTRACT_PATH_text(original_to, 'email') as original_to_email,
    JSON_EXTRACT_PATH_text(original_to, 'id') as original_to_id
from ct;
