canvas_columns = ['canvas_id',
                  'created_at',
                  'updated_at',
                  'name',
                  'description',
                  'archived',
                  'draft',
                  'schedule_type',
                  'first_entry',
                  'last_entry',
                  'channels',
                  'tags',
                  'variants',
                  'steps',
                  'extracted_at']

campaign_columns = ['campaign_id',
                    'created_at',
                    'updated_at',
                    'name',
                    'description',
                    'channels',
                    'tags',
                    'messages',
                    'conversion_behaviors',
                    'extracted_at']
