DROP TABLE IF EXISTS stg_external_apis_dl.ixopay_transactions;

CREATE TABLE stg_external_apis_dl.ixopay_transactions
    DISTKEY(uuid)
    SORTKEY(uuid)
AS WITH CTE AS (
SELECT
    uuid::VARCHAR(256),
    tenant_guid::VARCHAR(256),
    tenant_name::VARCHAR(256),
    master_tenant::VARCHAR(256),
    merchant_guid::VARCHAR(256),
    merchant_name::VARCHAR(256),
    connector_guid::VARCHAR(256),
    connector_name::VARCHAR(256),
    provider_guid::VARCHAR(256),
    provider_name::VARCHAR(256),
    purchase_id::VARCHAR(256),
    test_mode::VARCHAR(256),
    related_id::VARCHAR(256),
    broker_id::VARCHAR(256),
    meta_connector_guid::VARCHAR(256),
    meta_connector_name::VARCHAR(256),
    adapter::VARCHAR(256),
    method::VARCHAR(256),
    "type"::VARCHAR(256),
    "status"::VARCHAR(256),
    created_at::VARCHAR(256),
    modified_at::VARCHAR(256),
    initiated_by::VARCHAR(256),
    merchant_txid::VARCHAR(256),
    adapter_txid::VARCHAR(256),
    adapter_token::VARCHAR(256),
    adapter_processor_txid::VARCHAR(256),
    additional_id1::VARCHAR(256),
    additional_id2::VARCHAR(256),
    amount::double precision,
    currency::VARCHAR(256),
    base_amount::double precision,
    base_currency::varchar(256),
    "description"::varchar(256),
    statement_descriptor::varchar(256),
    extra_data::varchar(65535),
    callback_extra_data::varchar(10000),
    buyer_country::varchar(256),
    buyer_country_geopoint::varchar(256),
    "3d_secure"::varchar(256),
    transaction_indicator::varchar(256),
    incoming_settlement_state::varchar(256),
    outgoing_settlement_state::varchar(256),
    invoiceable::varchar(256),
    reconciliation_state::varchar(256),
    settlement_amount::double precision,
    settlement_currency::varchar(256),
    settlement_date::varchar(256),
    settlement_exchange_rate::double precision,
    is_recurring::varchar(256),
    registered_at::varchar(256),
    is_chargedback::varchar(256),
    chargedback_at::varchar(256),
    is_charged_reversed::varchar(256),
    chargeback_reversed_at::varchar(256),
    is_with_register::varchar(256),
    is_refunded::varchar(256),
    attempt::varchar(256),
    is_postback_delivered::varchar(256),
    return_data::varchar(256),
    items::varchar(256),
    fees::varchar(65535),
    customer::varchar(65535),
    creditcard::varchar(65535),
    errors::varchar(65535),
    status_history::varchar(65535),
    postprocessing::varchar(65535),
    row_number() OVER (PARTITION BY uuid ORDER BY extracted_at DESC) AS rn
FROM s3_spectrum_ixopay.transactions
    WHERE year = '{{ti.xcom_pull(key='year')}}'
    AND month = '{{ti.xcom_pull(key='month')}}'
    AND day = '{{ti.xcom_pull(key='day')}}'
    AND batch_id = '{{ti.xcom_pull(key='batch_id')}}')
SELECT
    uuid,
    tenant_guid,
    tenant_name,
    master_tenant,
    merchant_guid,
    merchant_name,
    connector_guid,
    connector_name,
    provider_guid,
    provider_name,
    purchase_id,
    test_mode,
    related_id,
    broker_id,
    meta_connector_guid,
    meta_connector_name,
    adapter,
    method,
    "type",
    "status",
    created_at,
    modified_at,
    initiated_by,
    merchant_txid,
    adapter_txid,
    adapter_token,
    adapter_processor_txid,
    additional_id1,
    additional_id2,
    amount,
    currency,
    base_amount,
    base_currency,
    "description",
    statement_descriptor,
    extra_data,
    callback_extra_data,
    buyer_country,
    buyer_country_geopoint,
    "3d_secure",
    transaction_indicator,
    incoming_settlement_state,
    outgoing_settlement_state,
    invoiceable,
    reconciliation_state,
    settlement_amount,
    settlement_currency,
    settlement_date,
    settlement_exchange_rate,
    is_recurring,
    registered_at,
    is_chargedback,
    chargedback_at,
    is_charged_reversed,
    chargeback_reversed_at,
    is_with_register,
    is_refunded,
    attempt,
    is_postback_delivered,
    return_data,
    items,
    fees,
    customer,
    creditcard,
    errors,
    status_history,
    postprocessing
FROM cte WHERE rn=1;
