SELECT
    CUSTOMER_ID:: VARCHAR AS CUSTOMER_ID,
    START_DATE_OF_FIRST_SUBSCRIPTION,
    (SUBSCRIPTION_REVENUE_DUE - SUBSCRIPTION_REVENUE_PAID) AS outstanding_payment,
    ACTIVE_SUBSCRIPTION_VALUE AS ASV,
    UPDATED_AT
FROM ods_production.customer_subscription_details
WHERE IS_BAD_CUSTOMER = False
AND CUSTOMER_ID IN {customer_ids};
