DROP TABLE IF EXISTS traffic.page_views;
CREATE TABLE traffic.page_views
  DISTKEY(page_view_id)
  SORTKEY(page_view_id)
AS 
SELECT 
	root_id,
 	snowplow_user_id AS anonymous_id,
	encoded_customer_id,
	customer_id::varchar,
	user_registration_date,
	customer_acquisition_date,
	customer_id_mapped::varchar,
	session_id,
	-- session_index,
	page_view_id,
	-- page_view_index,
	-- page_view_in_session_index,
	page_view_date,
	page_view_start,
	page_view_end,
	page_view_start_local,
	page_view_end_local,
	login_status,
	time_engaged_in_s,
	time_engaged_in_s_tier,
	vertical_pixels_scrolled,
	vertical_percentage_scrolled_tier,
	user_bounced,
	user_engaged,
 	page_url,
	page_urlpath,
	page_title,
	page_type,
	page_type_detail,
	page_width,
	page_height,
	store_id,
	store_name,
	store_label,
	referer_url,
	referer_url_host,
	referer_medium,
	referer_source,
	referer_term,
	marketing_medium,
	marketing_source,
	marketing_term,
	marketing_content,
	marketing_campaign,
	marketing_click_id,
	marketing_network,
	geo_country,
	geo_region_name,
	geo_city,
	geo_zipcode,
	geo_latitude,
	geo_longitude,
	geo_timezone,
	ip_address,
	platform,
	os_family,
	device,
	device_type,
	device_is_mobile,
	'snowplow_web'::VARCHAR AS traffic_source
FROM web.page_views_snowplow pv
WHERE page_view_start < '2023-05-01'

UNION

SELECT 
    root_id,
    anonymous_id,
    encoded_customer_id,
    customer_id::VARCHAR,
    user_registration_date,
    customer_acquisition_date,
    customer_id_mapped::VARCHAR,
    session_id::varchar,
    -- session_index,
    page_view_id,
    -- page_view_index,
    -- page_view_in_session_index,
    page_view_date,
    page_view_start,
    page_view_end,
    page_view_start_local::timestamp,
    page_view_end_local::timestamp,
    login_status,
    time_engaged_in_s,
    time_engaged_in_s_tier,
    vertical_pixels_scrolled::int,
    vertical_percentage_scrolled_tier,
    user_bounced,
    user_engaged,
    page_url,
    page_urlpath,
    page_title,
    page_type,
    page_type_detail,
    page_width::int,
    page_height::int,
    store_id,
    store_name,
    store_label,
    referer_url,
    referer_url_host,
    referer_medium,
    referer_source,
    referer_term,
    marketing_medium,
    marketing_source,
    marketing_term,
    marketing_content,
    marketing_campaign,
    marketing_click_id,
    marketing_network,
    geo_country,
    geo_region_name,
    geo_city,
    geo_zipcode,
    geo_latitude::float,
    geo_longitude::float,
    geo_timezone,
    ip_address,
    platform,
    os_family,
    device,
    device_type,
    device_is_mobile::bool,
    'segment_web'::VARCHAR AS traffic_source
FROM segment.page_views_web pv 
WHERE page_view_start >= '2023-05-01'

UNION

SELECT 
    root_id,
    anonymous_id,
    encoded_customer_id,
    customer_id::VARCHAR,
    user_registration_date,
    customer_acquisition_date,
    customer_id_mapped::VARCHAR,
    session_id::varchar,
    -- session_index,
    page_view_id,
    -- page_view_index,
    -- page_view_in_session_index,
    page_view_date,
    page_view_start,
    page_view_end,
    page_view_start_local::timestamp,
    page_view_end_local::timestamp,
    login_status,
    time_engaged_in_s,
    time_engaged_in_s_tier,
    vertical_pixels_scrolled::int,
    vertical_percentage_scrolled_tier,
    user_bounced,
    user_engaged,
    page_url,
    page_urlpath,
    page_title,
    page_type,
    page_type_detail,
    page_width::int,
    page_height::int,
    store_id,
    store_name,
    store_label,
    referer_url,
    referer_url_host,
    referer_medium,
    referer_source,
    referer_term,
    marketing_medium,
    marketing_source,
    marketing_term,
    marketing_content,
    marketing_campaign,
    marketing_click_id,
    marketing_network,
    geo_country,
    geo_region_name,
    geo_city,
    geo_zipcode,
    geo_latitude::float,
    geo_longitude::float,
    geo_timezone,
    ip_address,
    platform,
    os_family,
    device,
    device_type,
    device_is_mobile::bool,
    'segment_app'::VARCHAR AS traffic_source
FROM segment.page_views_app pv 
WHERE page_view_start >= '2023-09-01';

GRANT SELECT ON traffic.page_views TO tableau;
GRANT SELECT ON traffic.page_views TO redash_growth;
GRANT SELECT ON traffic.page_views TO ceyda_peker;
