--snapshot of everyday
DELETE FROM master.asset_historical
WHERE date = current_date - 1;

INSERT INTO master.asset_historical
SELECT 
asset_id,
customer_id,
subscription_id,
created_at,
updated_at,
asset_allocation_id,
asset_allocation_sf_id,
warehouse,
capital_source_name,
supplier,
first_allocation_store,
first_allocation_store_name,
first_allocation_customer_type,
serial_number,
ean,
product_sku,
asset_name,
asset_condition,
asset_condition_spv,
variant_sku,
product_name,
category_name,
subcategory_name,
brand,
invoice_url,
total_allocations_per_asset,
asset_order_number,
purchase_request_item_sfid,
purchase_request_item_id,
request_id,
purchased_date,
months_since_purchase,
days_since_purchase,
days_on_book,
months_on_book,
amount_rrp,
initial_price,
residual_value_market_price,
NULL AS residual_value_for_written_off_assets,--this data will be backfilled from luxco report everymonth
last_month_residual_value_market_price,
average_of_sources_on_condition_this_month,
average_of_sources_on_condition_last_available_price,
sold_price,
sold_date,
currency,
asset_status_original,
asset_status_new,
asset_status_detailed,
lost_reason,
lost_date,
last_allocation_days_in_stock,
last_allocation_dpd,
dpd_bucket,
subscription_revenue,
amount_refund,
subscription_revenue_due,
subscription_revenue_last_31day,
subscription_revenue_last_month,
subscription_revenue_current_month,
avg_subscription_amount,
max_subscription_amount,
payments_due,
last_payment_amount_due,
last_payment_amount_paid,
payments_paid,
shipment_cost_paid,
repair_cost_paid,
customer_bought_paid,
additional_charge_paid,
delivered_allocations,
returned_allocations,
max_paid_date,
office_or_sponsorships,
last_market_valuation,
last_valuation_report_date,
asset_value_linear_depr,
asset_value_linear_depr_book,
market_price_at_purchase_date,
active_subscription_id,
active_subscriptions_bom,
active_subscriptions,
acquired_subscriptions,
cancelled_subscriptions,
active_subscription_value,
acquired_subscription_value,
rollover_subscription_value,
cancelled_subscription_value,
shipping_country,
asset_sold_invoice,
invoice_date,
invoice_number,
invoice_total,
revenue_share,
first_order_id,
country,
city,
postal_code,
asset_cashflow_from_old_subscriptions,
last_active_subscription_id,
purchase_price_commercial,
supplier_locale,
current_date - 1 as date,
CURRENT_TIMESTAMP as snapshot_time
FROM master.asset
WHERE created_at < current_date;



--removing duplicates
