--snapshot of everyday
DELETE FROM master.subscription_payment_historical
WHERE date = current_date - 1;

INSERT INTO master.subscription_payment_historical
SELECT payment_group_id,
payment_id,
payment_sfid,
transaction_id,
resource_id,
movement_id,
psp_reference,
customer_id,
customer_type,
order_id,
asset_id,
brand,
allocation_id,
category_name,
subcategory_name,
subscription_id,
asset_was_delivered,
asset_was_returned,
created_at,
updated_at,
subscription_start_date,
billing_period_start,
billing_period_end,
payment_number,
payment_type,
due_date,
paid_date,
money_received_at,
failed_date,
attempts_to_pay,
subscription_payment_category,
default_new,
status,
payment_processor_message,
payment_method_details,
paid_status,
next_due_date,
dpd,
payment_method_detailed,
currency,
amount_due,
amount_paid,
amount_subscription,
amount_shipment,
amount_voucher,
amount_discount,
amount_tax,
tax_rate,
amount_overdue_fee,
amount_refund,
amount_chargeback,
debt_collection_handover_date,
result_debt_collection_contact,
is_dc_collections,
is_eligible_for_refund,
subscription_plan,
country_name,
store_label,
store_name,
store_short,
file_path,
burgel_risk_category,
covenant_exclusion_criteria,
invoice_url,
invoice_number,
invoice_date,
invoice_sent_date,
capital_source,
amount_overdue_pbi_adjusted,
payment_status_pbi_adjusted,
payment_method,
src_tbl,
current_date - 1 date
FROM master.subscription_payment
WHERE created_at < current_date;


--removing duplicates
