--we will skip the execution if the customer_id did not change
DELETE FROM hightouch_sources.gdpr_customer_info;

INSERT INTO hightouch_sources.gdpr_customer_info 
	(customer_id
	,created_at
	,subscription_limit
	,subscription_limit_change_date
	,customer_type
	,signup_language
	,default_locale
	,referral_code
	,email_subscribe
	,initial_subscription_limit
	,subscription_limit_defined_date
	,last_cart_product_names
	,delivered_allocations
	,returned_allocations
	,outstanding_purchase_price
	,active_subscription_product_names
	,active_subscription_subcategory
	,active_subscription_category
	,active_subscription_brand
	,ever_rented_asset_purchase_price
	,active_subscription_value
	,committed_subscription_value
	,active_subscriptions
	,payment_count
	,paid_subscriptions
	,refunded_subscriptions
	,failed_subscriptions
	,chargeback_subscriptions
	,subscriptions
	,start_date_of_first_subscription
	,first_subscription_store
	,first_subscription_acquisition_channel
	,subscription_durations
	,first_subscription_duration
	,subs_wearables
	,subs_drones
	,subs_cameras
	,subs_phones_and_tablets
	,subs_computers
	,subs_gaming
	,subs_audio
	,subs_other
	,first_subscription_product_category
	,ever_rented_products
	,ever_rented_sku
	,ever_rented_brands
	,ever_rented_subcategories
	,ever_rented_categories
	,clv
	,voucher_usage
	,subs_pag
	,subs_1m
	,subs_3m
	,subs_6m
	,subs_12m
	,subs_24m
	,customer_acquisition_cohort
	,customer_acquisition_subscription_id
	,customer_acquisition_rental_plan
	,customer_acquisition_category_name
	,customer_acquisition_subcategory_name
	,customer_acquisition_product_brand
	,rfm_score
	,rfm_segment
	,signup_country
	,crm_label
	,profile_status
	,crm_label_braze
	)
SELECT 
	customer_id
	,created_at
	,subscription_limit
	,subscription_limit_change_date
	,customer_type
	,signup_language
	,default_locale
	,referral_code
	,email_subscribe
	,initial_subscription_limit
	,subscription_limit_defined_date
	,last_cart_product_names
	,delivered_allocations
	,returned_allocations
	,outstanding_purchase_price
	,active_subscription_product_names
	,active_subscription_subcategory
	,active_subscription_category
	,active_subscription_brand
	,ever_rented_asset_purchase_price
	,active_subscription_value
	,committed_subscription_value
	,active_subscriptions
	,payment_count
	,paid_subscriptions
	,refunded_subscriptions
	,failed_subscriptions
	,chargeback_subscriptions
	,subscriptions
	,start_date_of_first_subscription
	,first_subscription_store
	,first_subscription_acquisition_channel
	,subscription_durations
	,first_subscription_duration
	,subs_wearables
	,subs_drones
	,subs_cameras
	,subs_phones_and_tablets
	,subs_computers
	,subs_gaming
	,subs_audio
	,subs_other
	,first_subscription_product_category
	,ever_rented_products
	,ever_rented_sku
	,ever_rented_brands
	,ever_rented_subcategories
	,ever_rented_categories
	,clv
	,voucher_usage
	,subs_pag
	,subs_1m
	,subs_3m
	,subs_6m
	,subs_12m
	,subs_24m
	,customer_acquisition_cohort
	,customer_acquisition_subscription_id
	,customer_acquisition_rental_plan
	,customer_acquisition_category_name
	,customer_acquisition_subcategory_name
	,customer_acquisition_product_brand
	,rfm_score
	,rfm_segment
	,signup_country
	,crm_label
	,profile_status
	,crm_label_braze
FROM master.customer 
WHERE customer_id IN (SELECT customer_id FROM staging_google_sheet.gdpr_input)
;