CREATE OR REPLACE VIEW dm_catman.v_product_structured_specifications AS
	SELECT 
		sku AS product_sku,
		name AS product_name,
		p2.category_name,
	    p2.subcategory_name,
		NULLIF(json_extract_path_text(structured_specifications,'aperture'),'') AS aperture,
		NULLIF(json_extract_path_text(structured_specifications, 'battery_life'),'') AS battery_life,
        NULLIF(json_extract_path_text(structured_specifications, 'brightness'),'') AS brightness,
        NULLIF(json_extract_path_text(structured_specifications, 'camera_resolution'),'') AS camera_resolution,
        NULLIF(json_extract_path_text(structured_specifications, 'case_size'),'') AS case_size,
        NULLIF(json_extract_path_text(structured_specifications, 'contrast_ratio'),'') AS contrast_ratio,
        NULLIF(json_extract_path_text(structured_specifications, 'fly_time'),'') AS fly_time,
        NULLIF(json_extract_path_text(structured_specifications, 'fps'),'') AS fps,
        NULLIF(json_extract_path_text(structured_specifications, 'lens_size'),'') AS lens_size,
        NULLIF(json_extract_path_text(structured_specifications, 'maximum_distance'),'') AS maximum_distance,
        NULLIF(json_extract_path_text(structured_specifications, 'megapixel'),'') AS megapixel,
        NULLIF(json_extract_path_text(structured_specifications, 'optical_zoom'),'') AS optical_zoom,
        NULLIF(json_extract_path_text(structured_specifications, 'ram'),'') AS ram,
        NULLIF(json_extract_path_text(structured_specifications, 'refresh_rate'),'') AS refresh_rate,
        NULLIF(json_extract_path_text(structured_specifications, 'response_time'),'') AS response_time,
        NULLIF(json_extract_path_text(structured_specifications, 'screen_size'),'') AS screen_size,
        NULLIF(json_extract_path_text(structured_specifications, 'speed'),'') AS speed,
        NULLIF(json_extract_path_text(structured_specifications, 'weight_limit'),'') AS weight_limit,
        NULLIF(json_extract_path_text(structured_specifications, 'weight'),'') AS weight,
        NULLIF(json_extract_path_text(structured_specifications, 'alexa_voice_control'),'') AS alexa_voice_control,
        NULLIF(json_extract_path_text(structured_specifications, 'apple_airplay_2'),'') AS apple_airplay_2,
        NULLIF(json_extract_path_text(structured_specifications, 'band_color'),'') AS band_color,
        NULLIF(json_extract_path_text(structured_specifications, 'band_material'),'') AS band_material,
        NULLIF(json_extract_path_text(structured_specifications, 'bluetooth'),'') AS bluetooth,
        NULLIF(json_extract_path_text(structured_specifications, 'case_material'),'') AS case_material,
        NULLIF(json_extract_path_text(structured_specifications, 'category_type'),'') AS category_type,
        NULLIF(json_extract_path_text(structured_specifications, 'collection'),'') AS collection,
        NULLIF(json_extract_path_text(structured_specifications, 'color'),'') AS color,
        NULLIF(json_extract_path_text(structured_specifications, 'compatibility'),'') AS compatibility,
        NULLIF(json_extract_path_text(structured_specifications, 'connectivity'),'') AS connectivity,
        NULLIF(json_extract_path_text(structured_specifications, 'control'),'') AS control,
        NULLIF(json_extract_path_text(structured_specifications, 'device'),'') AS device,
        NULLIF(json_extract_path_text(structured_specifications, 'display_type'),'') AS display_type,
        NULLIF(json_extract_path_text(structured_specifications, 'dj_equipmets'),'') AS dj_equipmets,
        NULLIF(json_extract_path_text(structured_specifications, 'dual_sim'),'') AS dual_sim,
        NULLIF(json_extract_path_text(structured_specifications, 'energy_efficiency'),'') AS energy_efficiency,
        NULLIF(json_extract_path_text(structured_specifications, 'esim'),'') AS esim,
        NULLIF(json_extract_path_text(structured_specifications, 'family'),'') AS family,
        NULLIF(json_extract_path_text(structured_specifications, 'features'),'') AS features,
        NULLIF(json_extract_path_text(structured_specifications, 'gpu_brand'),'') AS gpu_brand,
        NULLIF(json_extract_path_text(structured_specifications, 'gpu'),'') AS gpu,
        NULLIF(json_extract_path_text(structured_specifications, 'google_assistant_voice_control'),'') AS google_assistant_voice_control,
        NULLIF(json_extract_path_text(structured_specifications, 'hdr'),'') AS hdr,
        NULLIF(json_extract_path_text(structured_specifications, 'hi_res_audio'),'') AS hi_res_audio,
        NULLIF(json_extract_path_text(structured_specifications, 'inputs_outputs'),'') AS inputs_outputs,
        NULLIF(json_extract_path_text(structured_specifications, 'keyboard'),'') AS keyboard,
        NULLIF(json_extract_path_text(structured_specifications, 'lens_type'),'') AS lens_type,
        NULLIF(json_extract_path_text(structured_specifications, 'light_source'),'') AS light_source,
        NULLIF(json_extract_path_text(structured_specifications, 'maximum_resolution'),'') AS maximum_resolution,
        NULLIF(json_extract_path_text(structured_specifications, 'mount'),'') AS mount,
        NULLIF(json_extract_path_text(structured_specifications, 'multiroom'),'') AS multiroom,
        NULLIF(json_extract_path_text(structured_specifications, 'noise_cancelling'),'') AS noise_cancelling,
        NULLIF(json_extract_path_text(structured_specifications, 'office_headphones'),'') AS office_headphones,
        NULLIF(json_extract_path_text(structured_specifications, 'operating_mode'),'') AS operating_mode,
        NULLIF(json_extract_path_text(structured_specifications, 'operating_system_compatibility'),'') AS operating_system_compatibility,
        NULLIF(json_extract_path_text(structured_specifications, 'operating_system'),'') AS operating_system,
        NULLIF(json_extract_path_text(structured_specifications, 'os'),'') AS os,
        NULLIF(json_extract_path_text(structured_specifications, 'platforms'),'') AS platforms,
        NULLIF(json_extract_path_text(structured_specifications, 'playback'),'') AS playback,
        NULLIF(json_extract_path_text(structured_specifications, 'processor_brand'),'') AS processor_brand,
        NULLIF(json_extract_path_text(structured_specifications, 'processor_model'),'') AS processor_model,
        NULLIF(json_extract_path_text(structured_specifications, 'product_type'),'') AS product_type,
        NULLIF(json_extract_path_text(structured_specifications, 'projection_distance'),'') AS projection_distance,
        NULLIF(json_extract_path_text(structured_specifications, 'projector_use'),'') AS projector_use,
        NULLIF(json_extract_path_text(structured_specifications, 'resolution'),'') AS resolution,
        NULLIF(json_extract_path_text(structured_specifications, 'screen_type'),'') AS screen_type,
        NULLIF(json_extract_path_text(structured_specifications, 'sensor'),'') AS sensor,
        NULLIF(json_extract_path_text(structured_specifications, 'sport_headphones'),'') AS sport_headphones,
        NULLIF(json_extract_path_text(structured_specifications, 'stereo_sound_capable'),'') AS stereo_sound_capable,
        NULLIF(json_extract_path_text(structured_specifications, 'storage_capacity'),'') AS storage_capacity,
        NULLIF(json_extract_path_text(structured_specifications, 'style'),'') AS style,
        NULLIF(json_extract_path_text(structured_specifications, 'supported_platforms'),'') AS supported_platforms,
        NULLIF(json_extract_path_text(structured_specifications, 'type'),'') AS type,
        NULLIF(json_extract_path_text(structured_specifications, 'video_resolution'),'') AS video_resolution,
        NULLIF(json_extract_path_text(structured_specifications, 'voice_control'),'') AS voice_control,
        NULLIF(json_extract_path_text(structured_specifications, 'water_resistant'),'') AS water_resistant,
        NULLIF(json_extract_path_text(structured_specifications, 'wireless_capability'),'') AS wireless_capability,
        NULLIF(json_extract_path_text(structured_specifications, 'wireless_charging'),'') AS wireless_charging,
        NULLIF(json_extract_path_text(structured_specifications, 'with_controller'),'') AS with_controller,
	    ROW_NUMBER() over (ORDER BY(SELECT 1)) AS primary_key
	FROM stg_api_production.spree_products p
	INNER JOIN ods_production.product p2 
		ON p.id = p2.product_id 	
    WHERE is_valid_json(structured_specifications)
WITH NO SCHEMA binding 
;

GRANT SELECT ON dm_catman.v_product_structured_specifications TO hightouch;