# List of columns needed from the Invoices excel file
invoices_col_names = ['asset_name',
                      'category',
                      'product_group',
                      'status',
                      'channel',
                      'inventory_id',
                      'foxway_id',
                      'external_id',
                      'grover_id',
                      'payment_date',
                      'retail_price_gross',
                      'adv_shipping_cost_gross',
                      'retail_price_net',
                      'shipping_cost_net',
                      'rev_share_percent',
                      'rev_share_euro',
                      'goods_entrance',
                      'grading_cost',
                      'handling_cost',
                      'shipment_cost',
                      'return_handling_cost',
                      'transaction_fee_cost',
                      'campaign_cost',
                      'locked_device_cost',
                      'warranty_cost',
                      'repair_cost',
                      'shipment_processing_cost',
                      'zpue',
                      'adv_shipping_processing_cost',
                      'locked_processing_samsung',
                      'locked_processing_apple',
                      'kitting_refinement',
                      'kitting_wearable',
                      'kitting_12w_wearable',
                      'kitting_category_b_c',
                      'total_rev_share',
                      'total_opex',
                      'opex',
                      'total_additional_processes',
                      'total_billing',
                      'total_retail_price_net',
                      'total_payout',
                      'comment']

# List of required excel columns, in excel notation format
invoices_use_cols = 'A:N, P:Q, S:W, Y:Z, AB:AG, AI:AJ, AL:AO, AQ:AT, AV, AX:AY, BA'
