SELECT
	reporting_date AS "Reporting Date",
	asset_id AS "Asset ID",
	serial_number AS "Serial Number",
	brand AS "Asset Brand",
	asset_name AS "Asset Name",
	product_sku AS "Product SKU",
	warehouse AS "Warehouse",
	capital_source_name AS "Capital Source",
	category AS "Category",
	subcategory AS "Subcategory",
	purchased_date AS "Purchase Date",
	purchase_price AS "Initial Price",
	CONDITION AS "Condition",
	asset_added_to_portfolio_m_and_g AS "Asset added to Portfolio in Reporting Month",
	days_in_stock AS "Days In Stock",
	last_allocation_dpd AS "Days Past Due",
	dpd_bucket_r AS "Dpd Bucket",
	asset_position AS "Asset Position",
	asset_classification_m_and_g AS "Asset Classification",
	m_since_last_valuation_price AS "Months since Last Valuation",
	valuation_method AS "Valuation Method",
	original_valuation AS "Original Valuation",
	impairment_rate AS "Impairment Rate",
	final_valuation AS "Final Price",
	original_valuation - final_valuation AS "Impairments",
	committed_subscription_value AS "Committed Subscription Value",
	commited_sub_revenue_future AS "Committed Subscription Revenue Future",
	subscription_id AS "Subscription ID",
	--null for cancelled sub
	subscription_plan AS "Subscription Plan",
	--null for cancelled sub
	start_date::date AS "Subscription Starting Date",
	--null for cancelled sub
	maturity_date::date AS "Subscription Maturity Date",
	--null for cancelled sub
	committed_duration AS "Commited Duration",
	--null for cancelled sub
	current_duration_calculated AS "Current Duration",
	--null for cancelled sub
	outstanding_duration_calcuated AS "Remaining Duration",
	--null for cancelled sub
	effective_duration AS "Effective Duration",
	--null for cancelled sub
	current_subscription_amount AS "Current Subscription Amount",
	--null for cancelled sub
	total_subscriptions_per_asset AS "Total Subscriptions per Asset",
	customer_id AS "Customer ID",
	customer_type AS "Customer Type",
	customer_score,
	credit_buro,
	is_risky_customer,
	rentalco,
	country AS "Country",
	city AS "City",
	postal_code AS "Postal Code",
	customer_active_subscriptions AS "Customer Active Subscriptions",
	customer_net_revenue_paid AS "Customer Net Revenue Paid",
	customer_acquisition_month AS "Customer Acquisition Month",
	cust_acquisition_channel AS "Customer Acquisition Channel",
	subscription_revenue_paid_reporting_month AS "Subscription Revenue Paid Reporting Month",
	other_revenue_paid_reporting_month AS "Other Revenue Paid Reporting Month",
	total_asset_inflow_reporting_month AS "Total Asset Inflow Paid Reporting Month",
	refunds_chb_subscription_paid_reporting_month AS "Subscription Refunds & Chargebacks Paid Reporting Month",
	refunds_chb_others_paid_reporting_month_r AS "Other Refunds & Chargebacks Paid Reporting Month",
	total_refunds_chb_reporting_month AS "Total Refunds & Chargebacks Reporting Month",
	total_net_asset_inflow_reporting_month AS "Total Asset Net Inflow Reporting Month",
	subscription_revenue_due_reporting_month AS "Subscription Revenue Due Reporting Month",
	subscription_revenue_overdue_reporting_month AS "Subscription Revenue Overdue Reporting Month",
	--other_revenue_due_reporting_month as "Other Revenue Due Reporting Month",
	--other_revenue_overdue_reporting_month as "Other Revenue Overdue Reporting Month",
	--total_revenue_due_reporting_month as "Total Due Reporting Month",
	--total_revenue_overdue_reporting_month as "Total Overdue Balance Reporting Month",
	subscription_revenue_paid_lifetime AS "Subscription Revenue Paid Lifetime",
	other_charges_paid_lifetime_r AS "Other Revenue Paid Lifetime",
	total_asset_inflow_lifetime AS "Total Asset Inflow Lifetime",
	refunds_chb_subscription_paid_lifetime AS "Subscription Refunds & Chargebacks Paid Lifetime",
	refunds_chb_others_paid_lifetime_r AS "Other Refunds & Chargebacks Paid Lifetime",
	total_refunds_chb_lifetime AS "Total Refunds & Chargebacks Lifetime",
	total_net_inflow_lifetime AS "Total Asset Net Inflow Lifetime",
	subscription_revenue_due_lifetime AS "Subscription Revenue Due Lifetime",
	subscription_revenue_overdue_lifetime AS "Subscription Revenue Overdue Lifetime",
	--other_revenue_due_lifetime as "Other Revenue Due Lifetime",
	--other_revenue_overdue_lifetime as "Other Revenue Overdue Lifetime",
	--total_revenue_due_lifetime as "Total Due Lifetime",
	--overdue_balance_lifetime as "Total Overdue Balance Lifetime",
	is_sold AS "Asset is Sold",
	is_sold_reporting_month AS "Asset is Sold in Reporting Month",
	sold_price AS "Sell Price",
	sold_date AS "Sell Date",
	asset_status_detailed AS "Sale Status",
	--sold_asset_status_classification as "Sale Classification",
	last_market_valuation AS "Last Market Valuation",
	total_profit AS "Total Profit",
	CASE
		WHEN purchase_price = 0
		OR purchase_price IS NULL THEN 1
		ELSE return_on_asset / purchase_price
	END AS "Return On Asset",
	active_subscriptions AS "Active Subscriptions",
	active_subscriptions_bom AS "Active Subscriptions Bom",
	acquired_subscriptions AS "Acquired Subscriptions",
	rollover_subscriptions AS "Rollover Subscriptions",
	cancelled_subscriptions AS "Cancelled Subscriptions",
	active_subscriptions_eom AS "Active Subscriptions Eom",
	active_subscription_value AS "Active Subscription Value",
	acquired_subscription_value AS "Acquired Subscription Value",
	rollover_subscription_value AS "Rollover Subscription Value",
	cancelled_subscription_value AS "Cancelled Subscription Value",
	active_subscription_value_eom AS "Active Subscription Value Eom",
	months_rqd_to_own ,
	months_left_required_to_own,
	shifted_creation_cohort ,
	asset_purchase_discount_percentage,
	market_price_at_purchase_date ,
	asset_transfer,
	asset_value_type,
	asset_value_transfer,
	asset_transfer_date,
	avg_subscription_amount AS "Avg Subscription Amount",
	--null for cancelled sub
	max_subscription_amount AS "Max Subscription Amount",
	--null for cancelled sub
	customer_risk_category AS "Risk Category",
	date_to_own
FROM
	ods_spv_historical.luxco_reporting_202212 a
WHERE
	capital_source_name = 'SUSTAINABLE TECH RENTAL EUROPE II GMBH';
