UPDATE stg_salesforce.subscription_payment__c
SET
allocation__c = b.allocation__c,
amount_discount__c = b.amount_discount__c,
amount_f_debt__c = b.amount_f_debt__c,
amount_f_due__c = b.amount_f_due__c,
amount_f_due_without_taxes__c = b.amount_f_due_without_taxes__c,
amount_f_profit__c = b.amount_f_profit__c,
amount_f_revenue__c = b.amount_f_revenue__c,
amount_f_sales_tax__c = b.amount_f_sales_tax__c,
amount_f_sum__c = b.amount_f_sum__c,
amount_f_vat__c = b.amount_f_vat__c,
amount_fake__c = b.amount_fake__c,
amount_paid__c = b.amount_paid__c,
amount_refunded__c = b.amount_refunded__c,
amount_shipment__c = b.amount_shipment__c,
amount_subscription__c = b.amount_subscription__c,
amount_voucher__c = b.amount_voucher__c,
asset__c = b.asset__c,
can_recurrent_be_charged__c = b.can_recurrent_be_charged__c,
charge_id__c = b.charge_id__c,
charges__c = b.charges__c,
combined_monthly_invoice_url__c = b.combined_monthly_invoice_url__c,
createdbyid = b.createdbyid,
createddate = b.createddate,
currency__c = b.currency__c,
customer__c = b.customer__c,
customer_email__c = b.customer_email__c,
date_billing_end__c = b.date_billing_end__c,
date_billing_start__c = b.date_billing_start__c,
date_cancel__c = b.date_cancel__c,
date_debt_collection_handover__c = b.date_debt_collection_handover__c,
date_debt_collection_not_recoverable__c = b.date_debt_collection_not_recoverable__c,
date_debt_collection_requested__c = b.date_debt_collection_requested__c,
date_due__c = b.date_due__c,
date_failed__c = b.date_failed__c,
date_held__c = b.date_held__c,
date_invoice_sent__c = b.date_invoice_sent__c,
date_invoiced__c = b.date_invoiced__c,
date_paid__c = b.date_paid__c,
date_pending__c = b.date_pending__c,
date_refunded__c = b.date_refunded__c,
date_try_next__c = b.date_try_next__c,
exchange_rate__c = b.exchange_rate__c,
exchange_rate_capital_source__c = b.exchange_rate_capital_source__c,
f_asset_amount_debt__c = b.f_asset_amount_debt__c,
f_asset_amount_due__c = b.f_asset_amount_due__c,
f_asset_amount_due_without_tax__c = b.f_asset_amount_due_without_tax__c,
f_asset_amount_profit__c = b.f_asset_amount_profit__c,
f_capital_source_amount_debt__c = b.f_capital_source_amount_debt__c,
f_capital_source_amount_due__c = b.f_capital_source_amount_due__c,
f_capital_source_amount_due_without_tax__c = b.f_capital_source_amount_due_without_tax__c,
f_capital_source_amount_profit__c = b.f_capital_source_amount_profit__c,
f_debt_collection_status__c = b.f_debt_collection_status__c,
f_paid_debt_agency__c = b.f_paid_debt_agency__c,
f_paid_manually__c = b.f_paid_manually__c,
f_paid_type__c = b.f_paid_type__c,
f_rate_rrp__c = b.f_rate_rrp__c,
f_refund_type__c = b.f_refund_type__c,
failed_fully__c = b.failed_fully__c,
force_refunded_into_dc__c = b.force_refunded_into_dc__c,
invoice_number__c = b.invoice_number__c,
invoice_url__c = b.invoice_url__c,
is_dumb_payment__c = b.is_dumb_payment__c,
isdeleted = b.isdeleted,
lastactivitydate = b.lastactivitydate,
lastmodifiedbyid = b.lastmodifiedbyid,
lastmodifieddate = b.lastmodifieddate,
message__c = b.message__c,
name = b.name,
number__c = b.number__c,
order__c = b.order__c,
order_product__c = b.order_product__c,
overdue_fee_amount__c = b.overdue_fee_amount__c,
ownerid = b.ownerid,
payment_method__c = b.payment_method__c,
payment_method_details__c = b.payment_method_details__c,
payment_method_funding__c = b.payment_method_funding__c,
payment_method_id_1__c = b.payment_method_id_1__c,
payment_method_id_2__c = b.payment_method_id_2__c,
rate_sales_tax__c = b.rate_sales_tax__c,
rate_vat__c = b.rate_vat__c,
reason_cancel__c = b.reason_cancel__c,
reason_failed__c = b.reason_failed__c,
reason_held__c = b.reason_held__c,
reason_paid__c = b.reason_paid__c,
refund_blocked__c = b.refund_blocked__c,
refunded_greater__c = b.refunded_greater__c,
retry_with_the_same_payment_method__c = b.retry_with_the_same_payment_method__c,
should_create_invoice__c = b.should_create_invoice__c,
status__c = b.status__c,
subscription__c = b.subscription__c,
systemmodstamp = b.systemmodstamp,
tries_charge__c = b.tries_charge__c,
type__c = b.type__c,
x1st_warning_sent_date__c = b.x1st_warning_sent_date__c,
x2nd_warning_sent_date__c = b.x2nd_warning_sent_date__c,
x3rd_warning_sent_date__c = b.x3rd_warning_sent_date__c
FROM stg_skyvia.test_subscription_payment__c b
WHERE subscription_payment__c.id = b.id
AND true
	AND date(subscription_payment__c.lastmodifieddate)<current_date -  1
	AND b.lastmodifieddate > subscription_payment__c.lastmodifieddate;

-- subscription payment missing records 

insert into stg_salesforce.subscription_payment__c
SELECT id, ownerid, isdeleted, "name", createddate, createdbyid, lastmodifieddate, lastmodifiedbyid,
systemmodstamp, lastactivitydate,null as lastvieweddate, null as lastreferenceddate, amount_f_debt__c, 
amount_f_due__c, amount_f_profit__c, amount_f_revenue__c, amount_f_sum__c, amount_f_sales_tax__c, 
amount_f_vat__c, amount_paid__c, amount_discount__c, amount_refunded__c, amount_shipment__c, 
amount_subscription__c, amount_voucher__c, asset__c, charge_id__c, charges__c, currency__c, customer__c,
date_debt_collection_handover__c, date_debt_collection_requested__c, date_due__c, date_failed__c, date_held__c,
date_invoice_sent__c, date_invoiced__c, date_paid__c, date_refunded__c, date_try_next__c,
f_debt_collection_status__c, f_paid_debt_agency__c, f_paid_manually__c, f_refund_type__c, invoice_url__c, 
invoice_number__c, message__c, number__c, order__c, f_paid_type__c, payment_method__c, payment_method_id_1__c, 
payment_method_id_2__c, rate_sales_tax__c, rate_vat__c, reason_failed__c, reason_held__c, reason_paid__c, 
is_dumb_payment__c, status__c, tries_charge__c, type__c, allocation__c, date_debt_collection_not_recoverable__c, 
amount_fake__c, exchange_rate__c, can_recurrent_be_charged__c, exchange_rate_capital_source__c, date_cancel__c,
reason_cancel__c, order_product__c, amount_f_due_without_taxes__c, f_rate_rrp__c, 
retry_with_the_same_payment_method__c, f_capital_source_amount_due__c, f_capital_source_amount_due_without_tax__c, 
f_capital_source_amount_profit__c, f_capital_source_amount_debt__c, f_asset_amount_due__c, 
f_asset_amount_due_without_tax__c, f_asset_amount_profit__c, f_asset_amount_debt__c, customer_email__c,
subscription__c, date_billing_end__c, date_billing_start__c, failed_fully__c, date_pending__c,
payment_method_details__c, refund_blocked__c, should_create_invoice__c, payment_method_funding__c, 
refunded_greater__c, force_refunded_into_dc__c, combined_monthly_invoice_url__c, x1st_warning_sent_date__c, 
x2nd_warning_sent_date__c,
overdue_fee_amount__c, x3rd_warning_sent_date__c,null as allocation_status__c, null as date_chargedback__c, null as force_into_dc__c
FROM stg_skyvia.test_subscription_payment__c 
where id not in (select id from stg_salesforce.subscription_payment__c)
and id not in ('a09S70000046VOeIAM',
'a09S70000046j4zIAA',
'a09S70000046j8DIAQ',
'a09S70000046gS6IAI',
'a0907000008ffIPAAY',
'a0907000008ffIUAAY',
'a0907000008ffIZAAY',
'a0907000008ffIeAAI',
'a0907000008feXuAAI',
'a0907000008ffIAAAY',
'a0907000008ffIFAAY',
'a0907000008ffIKAAY',
'a0907000008feoWAAQ',
'a0907000008ffKVAAY',
'a0907000008ffKfAAI',
'a0907000008ffKpAAI',
'a0907000008ffKzAAI',
'a0907000008ffDeAAI',
'a0907000008ffDtAAI',
'a0907000008ffDyAAI',
'a0907000008ffE8AAI',
'a0907000008feUpAAI',
'a0907000008fexkAAA',
'a0907000008feRkAAI',
'a0907000008feVFAAY',
'a0907000008ffMCAAY',
'a0907000008ffMHAAY',
'a0907000008ffMMAAY',
'a0907000008ffMRAAY',
'a0907000008ff1IAAQ',
'a0907000008ff1NAAQ',
'a0907000008ff1XAAQ',
'a0907000008ff1mAAA',
'a0907000008ff2zAAA',
'a0907000008ff34AAA',
'a0907000008ff39AAA',
'a0907000008ff3EAAQ',
'a0907000006pmPbAAI',
'a0907000006ppBuAAI',
'a0907000006pFJlAAM',
'a0907000006pGUeAAM');
